version: '3.8'
  
services:
  cvquity-app:
    container_name: sme_mall_vue
    build: 
      dockerfile: Dockerfile
      context: .
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:8080'
